--- # Install JAva JDK SE11,and Maven

- hosts: ubuntu
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:

  - name: install JDK8
    apt:
      name: openjdk-8-jdk
      state: present
      update_cache: yes
    notify:
      - add $JAVA_HOME environment variable

  - name: unzip maven to user home dir
    unarchive:
      src: http://apache.lauf-forum.at/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
      dest: /home/ansible/
      remote_src: yes
    notify: 
      - remove maven archive
      - add maven bin directory to the PATH

  handlers:
  - name: add $JAVA_HOME environment variable
    shell: echo 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/' >> /etc/environment

  - name: add maven bin directory to the PATH
    shell: echo 'PATH="$PATH:/home/ansible/apache-maven-3.6.0/bin"' >> /etc/environment

  - name: remove maven archive
    file:
      path: /home/ansible/apache-maven-3.6.0-bin.tar.gz"
      state: absent
